const gridData = [
    {
        "label": "I am a genuine threat to society",
        "energy": 6,
        "pleasantness": 1,
        "color": 'darkred',
    },
    {
        "label": "(In Minecraft)",
        "energy": 6,
        "pleasantness": 2,
        "color": 'coral',
    },
    {
        "label": "Goblin mode",
        "energy": 6,
        "pleasantness": 3,
        "color": "lightcoral",
    },
    {
        "label": "Silly goose",
        "energy": 6,
        "pleasantness": 4,
        "color": 'lightsalmon',
    },
    {
        "label": "Let's gooooooo",
        "energy": 6,
        "pleasantness": 5,
        "color": "moccasin",
    },
    {
        "label": "LETS FUCKING GOOOOOOOO",
        "energy": 6,
        "pleasantness": 6,
        "color": "lemonchiffon",
    },
    {
        "label": "You've got to be fucking kidding me",
        "energy": 5,
        "pleasantness": 1,
        "color": "darkred",
    },
    {
        "label": "FUCK",
        "energy": 5,
        "pleasantness": 2,
        "color": "coral",
    },
    {
        "label": "Fuck it we ball",
        "energy": 5,
        "pleasantness": 3,
        "color": "lightcoral",
    },
    {
        "label": "Bitches love my mustache",
        "energy": 5,
        "pleasantness": 4,
        "color": "lightsalmon",
    },
    {
        "label": "We're so back",
        "energy": 5,
        "pleasantness": 5,
        "color": "moccasin",
    },
    {
        "label": "We're so fucking back",
        "energy": 5,
        "pleasantness": 5,
        "color": "lemonchiffon",
    },
    {
        "label": "I hate people",
        "energy": 4,
        "pleasantness": 1,
        "color": "darkred",
    },
    {
        "label": "I don't think we're going to make it out of the hood bro",
        "energy": 4,
        "pleasantness": 2,
        "color": "coral",
    },
    {
        "label": "*Internal screaming*",
        "energy": 4,
        "pleasantness": 3,
        "color": "lightcoral",
    },
    {
        "label": "It is what it is",
        "energy": 4,
        "pleasantness": 4,
        "color": "lightsalmon",
    },
    {
        "label": "We're gonna make it bro",
        "energy": 4,
        "pleasantness": 5,
        "color": "moccasin",
    },
    {
        "label": "Modelo time",
        "energy": 4,
        "pleasantness": 6,
        "color": "lemonchiffon",
    },
    {
        "label": "It's the kind of tired that sleep won't fix...",
        "energy": 3,
        "pleasantness": 1,
        "color": "slategray",
    },
    {
        "label": "It's just one of those days...",
        "energy": 3,
        "pleasantness": 2,
        "color": "lightsteelblue",
    },
    {
        "label": "yeah bro, I just need some sleep",
        "energy": 3,
        "pleasantness": 3,
        "color": "aliceblue",
    },
    {
        "label": "It really do be like sometimes",
        "energy": 3,
        "pleasantness": 4,
        "color": "#bce1ab",
    },
    {
        "label": "Straight chilling",
        "energy": 3,
        "pleasantness": 5,
        "color": "darkseagreen",
    },
    {
        "label": '"neat"',
        "energy": 3,
        "pleasantness": 6,
        "color": "#42610a",
    },
    {
        "label": "My mom would be sad",
        "energy": 2,
        "pleasantness": 1,
        "color": "slategray",
    },
    {
        "label": "It's so over",
        "energy": 2,
        "pleasantness": 2,
        "color": "lightsteelblue",
    },
    {
        "label": "This time I'm really gonna do it",
        "energy": 2,
        "pleasantness": 3,
        "color": "aliceblue",
    },
    {
        "label": "Anotha day, anotha dolla",
        "energy": 2,
        "pleasantness": 4,
        "color": "#bce1ab",
    },
    {
        "label": '"cool"',
        "energy": 2,
        "pleasantness": 5,
        "color": "darkseagreen",
    },
    {
        "label": "We vibing",
        "energy": 2,
        "pleasantness": 6,
        "color": "#42610a",
    },
    {
        "label": "I geuss that's it (Ronnie McNutt)",
        "energy": 1,
        "pleasantness": 1,
        "color": "slategray",
    },
    {
        "label": "My dog wouldn't understand",
        "energy": 1,
        "pleasantness": 2,
        "color": "lightsteelblue",
    },
    {
        "label": "One day somthing will kill me",
        "energy": 1,
        "pleasantness": 3,
        "color": "aliceblue",
    },
    {
        "label": "Comfortably numb",
        "energy": 1,
        "pleasantness": 4,
        "color": "#bce1ab",
    },
    {
        "label": '"aight"',
        "energy": 1,
        "pleasantness": 5,
        "color": "darkseagreen",
    },
    {
        "label": "I'm Bing chilling",
        "energy": 1,
        "pleasantness": 6,
        "color": "#42610a",
    },

]

export default gridData;